export default {
  dbUri: "DB_CONNECTION",
  environment: "NODE_ENV",
  fileUploadPath: "FILE_UPLOAD_PATH",
  geocoder: {
    apiKey: "GEOCODER_API_KEY",
    provider: "GEOCODER_PROVIDER",
  },
  jwtCookieExpire: "JWT_COOKIE_EXPIRE",
  jwtExpire: "JWT_EXPIRE",
  jwtSecret: "JWT_SECRET",
  maxFileUpload: "MAX_FILE_UPLOAD",
  port: "PORT",
  smtpHost: "SMTP_HOST",
  smtpPort: "SMTP_PORT",
  smtpEmail: "SMTP_EMAIL",
  smtpPassword: "SMTP_PASSWORD",
  fromEmail: "FROM_EMAIL",
  fromName: "FROM_NAME",
};
